apiVersion: v1
kind: Pod
metadata:
  name: raider-edera
spec:
  hostPID: true
  runtimeClassName: edera
  containers:
  - name: raider
    image: ubuntu:latest
    command: ["/bin/sh"]
    securityContext:
      privileged: true
    args: ["-c", "while true; do sleep 10;done"]
    tty: true
