apiVersion: v1
kind: Pod
metadata:
  name: memramp-edera
spec:
  runtimeClassName: edera
  containers:
  - name: memramp-edera
    image: denhamparry/memramp:latest
    env:
    - name: TESTING_MB
      value: "5"
  restartPolicy: Never
